version: "3.8"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    env_file:
      - docker.env
    ports:
      - "8081:3000"

  postgres:
    image: postgres:latest
    ports:
      - "35000:5432"
    env_file:
      - docker.env

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
